name: Executing Action between Repositories (TS)
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: kumvijaya/ts-action@v1.2
        with:
          greetName: 'Mona'